name: Deploy Wijekoon Distributors Backend to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Wijekoon Distributors Backend
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH agent
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      # Test SSH connection
      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} "echo 'SSH connection successful!'"

      # Debug PATH and npm availability
      - name: Test PATH and npm availability
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            set -e
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm use node
            echo "Node version: $(node -v)"
            echo "npm version: $(npm -v)"
          EOF

      # Deploy Wijekoon Distributors Backend to Droplet
      - name: Deploy Wijekoon Distributors Backend to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            set -e
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm use node
            cd /var/www/wijekoon-distributors/backend

            # Clean previous build
            rm -rf dist
            git reset --hard
            git pull origin main

            # Install dependencies
            npm install --force

            # Run linting
            npm run lint

            # Build the project
            npm run build

            # Memory optimization: Set node memory limit to 512MB
            export NODE_OPTIONS="--max_old_space_size=512"

            # Restart the PM2 process if it's already running or start a new one
            pm2 describe "wd-server" >/dev/null 2>&1 || pm2 start npm --name "wd-server" -- start
            pm2 restart "wd-server" --update-env

            # Save the PM2 process list and environment
            pm2 save

            # Clean up unused npm and node_modules cache to free up memory
            npm cache clean --force
          EOF

      # Restart Nginx
      - name: Restart Nginx
        run: |
          ssh -o ServerAliveInterval=60 -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            sudo systemctl restart nginx.service
          EOF

      # Logout all users except for current session
      - name: Logout all users except for current session
        run: |
          ssh -o ServerAliveInterval=60 -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            # Get the current user's PID
            current_pid=$(ps -u $(whoami) -o pid= | grep -v $$)

            # Loop through the PIDs and kill them if they aren't the current session
            for pid in $current_pid; do
              # Check if it's not the current SSH session PID
              if [ "$pid" != "$$" ]; then
                echo "Killing PID: $pid"
                sudo kill -9 $pid || echo "Failed to kill PID: $pid"
              fi
            done
          EOF
      
