name: Deploy Wijekoon Distributors Backend to Droplet

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    name: Wijekoon Distributors QA Backend Deployment
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # ✅ Install dependencies and build the backend
      - name: Install dependencies and build backend
        run: |
          cd backend
          npm install
          npm run build
          tar -czf backend-dist.tar.gz dist

      # ✅ Set up SSH agent
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      # ✅ Transfer only the `dist` folder to the VPS
      - name: Transfer Backend Build to VPS
        run: |
          rsync -avz --progress backend/backend-dist.tar.gz ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}:/tmp/

      # ✅ Deploy Backend on VPS (Extract `dist` and Restart Backend)
      - name: Deploy Backend to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            set -e
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm use node

            cd /var/www/qa/qa-wd-server

            # Remove old dist folder and extract new one
            rm -rf dist
            tar -xzf /tmp/backend-dist.tar.gz

            # Restart backend using PM2
            pm2 restart "wd-server-qa" --update-env
            pm2 save

            # Clean up temporary files
            rm /tmp/backend-dist.tar.gz
          EOF

      # ✅ Restart Nginx (from your original workflow)
      - name: Restart Nginx
        run: |
          ssh -o ServerAliveInterval=60 -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            sudo systemctl restart nginx.service
          EOF
